# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
	{
		:name => "nas1",
		:eth1 => "192.168.33.11",
		:script => "install1.sh",
	},
	{
		:name => "nas2",
		:eth1 => "192.168.33.12",
		:script => "install1.sh",
	},
	{
		:name => "nas3",
		:eth1 => "192.168.33.13",
		:script => "install2.sh",
	}
]

Vagrant.configure(2) do |config|


	config.vm.box = "ubuntu/trusty64"

	boxes.each do |opts|
		config.vm.define opts[:name] do |config|
			config.vm.hostname = opts[:name]
			config.vm.network "private_network", ip: opts[:eth1]
			config.vm.provision "shell", path: opts[:script]
		end
	end

  #config.vm.provider :virtualbox do |vb|
  #	vb.gui = true
  #end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  #config.vm.network "private_network", ip: "192.168.33.2"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  #config.vm.synced_folder ".", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  #config.vm.provision "shell", path: "./install.sh"
end
